name: "🐛 Signaler un bug"
description: "Signale un bug sur le site web."
title: "[Bug]: "
labels: ["bug: unconfirmed"]
body:
  - type: textarea
    attributes:
      label: Résumé
      description: |
        Un résumé clair et concis du bug.
      placeholder: |
        Exemple de rapport de bug :
        Lorsque je clique sur le bouton « Envoyer » des retours, rien ne se passe.
    validations:
      required: true
  - type: input
    attributes:
      label: Page
      description: |
        Sur quelle page avez-vous constaté le bug ?
      placeholder: |
        https://fr.react.dev/
    validations:
      required: true
  - type: textarea
    attributes:
      label: Détails
      description: |
        Veuillez fournir tout détail complémentaire utile sur ce bug.
      placeholder: |
        Exemples de détails :
        Le bouton « Envoyer » ne réagit pas. J'ai tenté de rafraîchir la page et d'utiliser un autre navigateur, mais le problème persiste.
    validations:
      required: false
