name: "📄 Suggérer un nouveau framework"
description: "Je suis l'auteur·e d'unframework et j'aimerais qu'il fasse partie des frameworks recommandés."
title: "[Framework]: "
labels: ["type: framework"]
body:
  - type: markdown
    attributes:
      value: |
        ## Candidature pour l'inclusion d'un framework React recommandé

        _Ce formulaire s'adresse aux auteur·es de framework qui souhaitent candidater pour qu'il fasse partie de la liste des [frameworks React](https://react.dev/learn/start-a-new-react-project) recommandés. Si vous n'êtes pas l'auteur·e du framework, contactez ses auteur·es pour leur suggérer de candidater._

        Lorsque nous recommandons un framework, nous le faisons afin que les développeur·ses puissent démarrer avec un projet React qui s'occupe d'entrée de jeu de sujets récurrents tels que la découpe de code, le chargement de données, le routage et la génération du HTML, sans avoir à fournir un travail complémentaire. Nous estimons que ça permettra aux gens de démarrer plus vite avec React, et de faire monter leur application à l'échelle en production.

        Même si nous comprenons bien que de nombreux frameworks aimeraient être inclus dans la liste, cette page n'est pas là pour faire la publicité de tous les frameworks React potentiels, ou de tous les frameworks auxquels React peut être intégré. Il existe de nombreux superbes frameworks capables d'intégrer React mais que nous ne listons pas dans nos guides.  Les frameworks que nous recommandons ont investi de façon significative dans l'écosystème React, et collaboré avec l'équipe React pour être compatible avec notre [vision d'une architecture React full-stack](https://fr.react.dev/learn/start-a-new-react-project#which-features-make-up-the-react-teams-full-stack-architecture-vision).
        
        Pour être inclus dans la liste, un framework doit satisfaire les critères suivants :

        - **Open-source et gratuit** : il doit être en logiciel libre et son utilisation gratuite.
        - **Bonne maintenance** : il doit être activement maintenu, avec correctifs et améliorations.
        - **Communauté active** : il doit disposer d'une communauté suffisamment large et vivante pour aider ses utilisateurs.
        - **Adoption facile** : il doit disposer d'étapes claires pour l'installation de la version React du framework.
        - **Compatible avec l'écosystème** : il doit prendre en charge l'ensemble des bibliothèques et outils de l'écosystème React.
        - **Auto-hébergement possible** : il doit permettre l'auto-hébergement d'applications sans que cela en limite les fonctionnalités.
        - **Expérience de développement (DX)** : il doit permettre aux développeur·ses d'être productif·ves grâce à des fonctionnalités telles que _Fast Refresh_.
        - **Expérience utilisateur (UX)** : il doit fournir des solutions intégrées aux problématiques usuelles telles que le routage et le chargement de données.
        - **Compatible avec notre vision de l'avenir de React**. React évolue avec le temps, et les frameworks qui ne s'alignent pas avec la direction que prend React risquent au fil du temps d'isoler leurs utilisateurs de l'écosystème React principal.  Pour vous inclure sur cette page, nous devons être confiants dans la capacité du framework à placer ses utilisateurs durablement sur le chemin du succès avec React.

        Notez bien que nous avons déjà passé en revue la plupart des frameworks populaires disponibles pour le moment, il est donc peu probable que nous n'ayons pas encore examiné votre framework. Mais si vous pensez que nous avons loupé quelque chose, veuillez remplir le formulaire ci-dessous.
  - type: input
    attributes:
      label: Nom
      description: |
        Quel est le nom de votre framework ?
    validations:
      required: true
  - type: input
    attributes:
      label: Page d'accueil
      description: |
        Quelle est l'URL de votre page d'accueil ?
    validations:
      required: true
  - type: input
    attributes:
      label: Instructions d'installation
      description: |
        Quelle est l'URL de votre guide de démarrage ?
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Votre framework est-il open source ?
      description: |
        Nous ne recommandons que les frameworks open source et gratuits.
      options:
        - 'Non'
        - 'Oui'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Maintenance active
      description: |
        Veuillez décrire (en anglais) en quoi votre framework est activement maintenu.  Fournissez des exemples récents de versions publiées, correctifs et améliorations.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Communauté active
      description: |
        Veuillez décrire (en anglais) votre communauté.  Indiquez-en la taille et fournissez des liens sur les ressoures communautaires.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Adoption facile
      description: |
        Veuillez décrire (en anglais) comment une personne peut installer votre framework avec React.  Fournissez les liens adéquats vers votre documentation.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Compatibilité avec l'écosystème
      description: |
        Veuillez décrire (en anglais) toute limite connue que votre framework aurait vis-à-vis de l'écosystème React. Indiquez toute bibliothèque ou tout outil dont vous savez qu'il n'est pas compatible avec votre framework.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Auto-hébergement
      description: |
        Veuillez décrire (en anglais) en quoi votre framework permet l'auto-hébergement.  Indiquez toute limitation connue de fonctionnalités dans le cadre de l'auto-hébergement.  Indiquez aussi s'il faut un serveur pour déployer votre framework.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expérience de développement (DX)
      description: |
        Veuillez décrire (en anglais) en quoi votre framework permet une super expérience de développeemnt. Indiquez toute limite connue aux fonctionnalités telles que les outils de développement React, ceux de Chrome ou encore le Fast Refresh.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expérience utilisateur (UX)
      description: |
        Veuillez décrire (en anglais) en quoi votre framework aide les gens à créer une expérience utilisateur de grande qualité, en s'occupant directement des problématiques courantes.  Indiquez par exemple en quoi vous gérez nativement la découpe de code, le routage, la génération de HTML ou le chargement de données d'une façon qui évite par défaut les cascades de requêtes client/serveur.  Détaillez la façon dont vous permettez des approches telles que SSG ou SSR.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Compatible avec notre vision de l'avenir de React
      description: |
        Veuillez décrire (en anglais) en quoi votre framework est aligné avec notre vision de l'avenir de React. Indiquez comment votre framework évoluera avec React, et quels sont vos plans pour prendre en charge les fonctionnalités à venir de React telles que les React Server Components.
    validations:
      required: true
